/* Generated by Together */

package com.miw.model;


public class EquipoExtra {

	private int id;
	private String description;
	private int cantidad;
	
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	
	public int getCantidad() {
		return cantidad;
	}
	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}
	public EquipoExtra(int id, String description) {
		super();
		this.id = id;
		this.description = description;
		
	}
	public EquipoExtra() {
		super();
		// TODO Auto-generated constructor stub
	}
}
