/* Generated by Together */

package impl.miw.business.viajemanager;



import java.util.Vector;

import org.springframework.beans.factory.annotation.Autowired;

import com.miw.business.ViajeManagerService;
import com.miw.model.Viaje;
import com.miw.persistence.ViajeDataService;




public class ViajeManager implements ViajeManagerService {

	@Autowired
	private ViajeDataService viajeDataService = null;
	

	

	public void setViajeDataService(ViajeDataService viajeDataService) {
		System.out.println("Persistencia Viaje");
		this.viajeDataService = viajeDataService;
	}

	public Vector<Viaje> getViajes() throws Exception {
			
		return viajeDataService.getViajes();
	}
	
	public Vector<String> getCiudades(boolean tipo) throws Exception{
	
		return viajeDataService.getCiudades(tipo);
	}
	public Vector<Viaje> getViajesSeleccionado(String ori,String dest,String fech, int numPasajeros) throws Exception{
				
		return viajeDataService.getViajesSeleccionado(ori,dest,fech,numPasajeros);
		
	}

	public void reducirPasajeros(int idviaje) {
		try {
			viajeDataService.reducirPasajeros(idviaje);
		} catch (Exception e) {
 			e.printStackTrace();
		}
		
	}

	public Viaje getViajeById(int id) throws Exception {
 		return viajeDataService.getViajeById(id);
	}
}
