/* Generated by Together */

package com.miw.model;

import javax.validation.constraints.NotEmpty;


public class CancelaReserva {
	
	@NotEmpty
	private String localizador;
    @NotEmpty
    private String email;
    
	public String getLocalizador() {
		return localizador;
	}
	public void setLocalizador(String localizador) {
		this.localizador = localizador;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
    
    
    
}
