/* Generated by Together */

package com.miw.model;

import java.util.Date;

public class Historial {


	private String localizador;
	private String email;
	private String origenIda;
	private String destinoIda;
	private Date fechaIda;
	private String horarioIda;
	private String origenVuelta;
	private String destinoVuelta;
	private Date fechaVuelta;
	private String horarioVuelta;
	private int pasajeros;
	private double precio;
	
	public String getLocalizador() {
		return localizador;
	}
	public void setLocalizador(String localizador) {
		this.localizador = localizador;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getOrigenIda() {
		return origenIda;
	}
	public void setOrigenIda(String origenIda) {
		this.origenIda = origenIda;
	}
	public String getDestinoIda() {
		return destinoIda;
	}
	public void setDestinoIda(String destinoIda) {
		this.destinoIda = destinoIda;
	}
	public Date getFechaIda() {
		return fechaIda;
	}
	public void setFechaIda(Date fechaIda) {
		this.fechaIda = fechaIda;
	}
	public String getHorarioIda() {
		return horarioIda;
	}
	public void setHorarioIda(String horarioIda) {
		this.horarioIda = horarioIda;
	}
	public String getOrigenVuelta() {
		return origenVuelta;
	}
	public void setOrigenVuelta(String origenVuelta) {
		this.origenVuelta = origenVuelta;
	}
	public String getDestinoVuelta() {
		return destinoVuelta;
	}
	public void setDestinoVuelta(String destinoVuelta) {
		this.destinoVuelta = destinoVuelta;
	}
	public Date getFechaVuelta() {
		return fechaVuelta;
	}
	public void setFechaVuelta(Date fechaVuelta) {
		this.fechaVuelta = fechaVuelta;
	}
	public String getHorarioVuelta() {
		return horarioVuelta;
	}
	public void setHorarioVuelta(String horarioVuelta) {
		this.horarioVuelta = horarioVuelta;
	}
	public int getPasajeros() {
		return pasajeros;
	}
	public void setPasajeros(int pasajeros) {
		this.pasajeros = pasajeros;
	}
	public double getPrecio() {
		return precio;
	}
	public void setPrecio(double precio) {
		this.precio = precio;
	}

	
	



}
