/* Generated by Together */

package com.miw.model;

//import java.util.ArrayList;
import java.util.Date;

public class Reserva {


	private String localizador;
	private String nombre;
	private String apellidos;
	private String dni;
	private String email;
 	private String seguro;
	
	private String [] equipaje;
	private String tipoId;
	private String idViajeIda;
	private String idViajeVuelta;
	
	
	public String getLocalizador() {
		return localizador;
	}
	public void setLocalizador(String localizador) {
		this.localizador = localizador;
	}
	public String getNombre() {
		return nombre;
	}
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	public String getApellidos() {
		return apellidos;
	}
	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}
	public String getDni() {
		return dni;
	}
	public void setDni(String dni) {
		this.dni = dni;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getSeguro() {
		return seguro;
	}
	public void setSeguro(String seguro) {
		this.seguro = seguro;
	}
	public String[] getEquipaje() {
		return equipaje;
	}
	public void setEquipaje(String[] equipaje) {
		this.equipaje = equipaje;
	}
	public String getTipoId() {
		return tipoId;
	}
	public void setTipoId(String tipoId) {
		this.tipoId = tipoId;
	}
	public String getIdViajeIda() {
		return idViajeIda;
	}
	public void setIdViajeIda(String idViajeIda) {
		this.idViajeIda = idViajeIda;
	}
	public String getIdViajeVuelta() {
		return idViajeVuelta;
	}
	public void setIdViajeVuelta(String idViajeVuelta) {
		this.idViajeVuelta = idViajeVuelta;
	}
	 
	   
	 

}
