/* Generated by Together */

package impl.miw.business.contadormanager;

import org.springframework.beans.factory.annotation.Autowired;
import com.miw.business.ContadorManagerService;
import com.miw.model.Contador;
import com.miw.persistence.ContadorDataService; 


public class ContadorManager implements ContadorManagerService {


	@Autowired
	private ContadorDataService contadorDataService;

	public int incrementar(Contador count) {
 		return contadorDataService.incrementar(count);
	}





}
