/* Generated by Together */

package impl.miw.business.reservamanager;


import java.util.Vector;

import org.springframework.beans.factory.annotation.Autowired;


import com.miw.business.ReservaManagerService;
import com.miw.model.Reserva;
import com.miw.persistence.ReservaDataService;


public class ReservaManager implements ReservaManagerService {

	@Autowired
	private ReservaDataService reservaDataService = null;
	

	

	public void setReservaDataService(ReservaDataService reservaDataService) {
		System.out.println("Persistencia reserva");
		this.reservaDataService = reservaDataService;
	}

	public Vector<Reserva> getReservas() throws Exception {
		
		Vector<Reserva> reservas = reservaDataService.getReservas();
		
		return reservas;
	}
}
