/* Generated by Together */

package com.miw.dto;


public class PreReservaDTO {

	private int id;
	private String description;
	private int cantidad;
	
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	
	public int getCantidad() {
		return cantidad;
	}
	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}
	public PreReservaDTO(int id, String description) {
		super();
		this.id = id;
		this.description = description;
		
	}
	public PreReservaDTO() {
		super();
		// TODO Auto-generated constructor stub
	}
}
